# Generated by Django 5.2.6 on 2025-09-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "posting_image",
                    models.ImageField(blank=True, null=True, upload_to="postings/"),
                ),
                ("posting_image_url", models.URLField(blank=True, null=True)),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("paid", "paid"),
                            ("free", "free"),
                            ("negotiable", "negotiable"),
                        ],
                        default="negotiable",
                        max_length=12,
                    ),
                ),
                ("price_amount", models.IntegerField(blank=True, null=True)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="postings", to="categories.category"
                    ),
                ),
            ],
        ),
    ]
