# Generated by Django 5.2.6 on 2025-09-12 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("postings", "0001_initial"),
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posting",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="postings",
                to="spaces.space",
            ),
        ),
    ]
