# Generated by Django 5.2.6 on 2025-09-12 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("postings", "0001_initial"),
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("artist", "artist"), ("space", "space")],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("is_free_allowed", models.BooleanField(blank=True, null=True)),
                ("is_performed_confirmed", models.BooleanField(blank=True, null=True)),
                ("is_accepted", models.BooleanField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions_as_artist",
                        to="artists.artist",
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions",
                        to="postings.posting",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions_as_space",
                        to="spaces.space",
                    ),
                ),
            ],
        ),
    ]
