# Generated by Django 5.2.6 on 2025-09-12 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("equipmentcategories", "0001_initial"),
        ("spaceequipments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Space",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("place_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("kakao_map_link", models.URLField(max_length=500)),
                (
                    "custom_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("capacity_seated", models.IntegerField(blank=True, null=True)),
                ("capacity_standing", models.IntegerField(blank=True, null=True)),
                (
                    "business_registration_number",
                    models.CharField(max_length=20, unique=True),
                ),
                ("atmosphere", models.JSONField(blank=True, default=list)),
                (
                    "place_image",
                    models.ImageField(blank=True, null=True, upload_to="spaces/place/"),
                ),
                ("place_image_url", models.URLField(blank=True, null=True)),
                (
                    "place_region",
                    models.CharField(
                        blank=True, editable=False, max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="main_category_spaces",
                        to="categories.category",
                    ),
                ),
                (
                    "equipments",
                    models.ManyToManyField(
                        blank=True,
                        through="spaceequipments.SpaceEquipment",
                        to="equipmentcategories.equipmentcategory",
                    ),
                ),
                (
                    "preferred_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preferred_spaces",
                        to="categories.category",
                    ),
                ),
            ],
        ),
    ]
