# Generated by Django 5.2.6 on 2025-09-12 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("likes", "0001_initial"),
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_by",
                to="spaces.space",
            ),
        ),
    ]
