# Generated by Django 5.2.6 on 2025-09-12 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipmentcategories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_equipment_links",
                        to="equipmentcategories.equipmentcategory",
                    ),
                ),
            ],
        ),
    ]
