# Generated by Django 5.2.6 on 2025-09-12 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spaceequipments", "0001_initial"),
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spaceequipment",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="space_equipment_links",
                to="spaces.space",
            ),
        ),
    ]
