# Generated by Django 5.2.6 on 2025-09-12 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artistequipments", "0001_initial"),
        ("categories", "0001_initial"),
        ("equipmentcategories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True, null=True)),
                ("number_of_members", models.IntegerField(default=1)),
                (
                    "custom_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("portfolio_links", models.JSONField(blank=True, default=list)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="artists/profile/"
                    ),
                ),
                ("profile_image_url", models.URLField(blank=True, null=True)),
                ("region", models.JSONField(blank=True, default=list)),
                ("desired_pay", models.IntegerField(blank=True, null=True)),
                ("is_free_allowed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="categories.category",
                    ),
                ),
                (
                    "equipments",
                    models.ManyToManyField(
                        blank=True,
                        through="artistequipments.ArtistEquipment",
                        to="equipmentcategories.equipmentcategory",
                    ),
                ),
            ],
        ),
    ]
