# Generated by Django 5.2.6 on 2025-09-12 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artistequipments", "0001_initial"),
        ("artists", "0001_initial"),
        ("equipmentcategories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistequipment",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist_equipment_links",
                to="artists.artist",
            ),
        ),
        migrations.AddField(
            model_name="artistequipment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist_equipment_links",
                to="equipmentcategories.equipmentcategory",
            ),
        ),
    ]
